version: '3'
networks:
  default:
    driver: bridge
services:
  app:
    build: .
    volumes:
       - .:/usr/src/user-balance-app
  beanstalkd:
    build: ./docker/beanstalkd
    ports:
      - "11300:11300"
  mysql:
    image: mysql:${MYSQL_VERSION}
    volumes:
      - ./data/db/data:/var/lib/mysql
      - ./data/db/dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: mysqld
    ports:
      - "3306:3306"
    expose:
      - "3306"
